apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::762107918466:role/eksctl-eksctl-demo-nodegroup-ng-a-NodeInstanceRole-1UVS6JVIBFEB
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::762107918466:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-20T15:41:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1746"
  uid: 67b410ea-270e-466d-b259-4d7dd5f8859c
